### ISSUE TITLE
Frontend - List async courses beneath the calendar

### ISSUE THREAD

**Issue by va9id** [ConnorMarcus/CarletonClassScheduler#105]
**remove duplicate schedules that have different async sections**

**Comment by ConnorMarcus** [comment]
The issue with the way we did this is that it is unclear when you are supposed to take an async with a schedule. For example, consider the CHEM 1001 course in Fall 2023. It has Lecture sections A, B, and E and several lab sections (some of which are async). For lecture section A (which requires CHEM 1001 A1 or A2 or A3 or A4 or A5 or A6 or A7 or G1) the calendar will show the following:
![image](https://github.com/ConnorMarcus/CarletonClassScheduler/assets/73544123/b6a7702e-4c7c-4254-83a2-bd88c8073178)
 
It is a bit unclear that lab section G1 and G2 should not be taken along with what is shown on the calendar. Also, if you look at schedule 8 that it generates, it will show no lab sections on the calendar (since this schedule was generated with the async lab section G1), which is very unclear that G1 needs to be taken:
![image](https://github.com/ConnorMarcus/CarletonClassScheduler/assets/73544123/8052f9b9-2361-4e55-ab5e-bbbf6ef07522)

Maybe we should think about a different approach for this.

**Comment by va9id** [comment]
Issue has been addressed
